name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          yarn install
          yarn docs:build

      - name: Check dist folder
        run: ls -l .vitepress/dist

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.0
        with:
          debug: true
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ".vitepress/dist/"
          target: "/data/aidenai.io"
          overwrite: true
